# Generated by Django 5.0.3 on 2024-11-28 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='الإجراء')),
                ('model_name', models.CharField(max_length=200, verbose_name='اسم النموذج')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف العنصر')),
                ('user', models.CharField(max_length=200, verbose_name='المستخدم')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('details', models.TextField(blank=True, null=True, verbose_name='تفاصيل')),
            ],
            options={
                'verbose_name': 'سجل',
                'verbose_name_plural': 'السجلات',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LeaseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإيجار الشهري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'عقد إيجار',
                'verbose_name_plural': 'عقود الايجار',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Notifiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المبني')),
                ('address', models.TextField(verbose_name='عنوان المبني')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='building_images/', verbose_name='صورة المبني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مبنى',
                'verbose_name_plural': 'المباني',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='rental_mana_name_f1629b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='وصف المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='تاريخ المصروف')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.building', verbose_name='المبنى')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصاريف',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/', verbose_name='الملف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rental_management.leasecontract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.leasecontract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
            },
        ),
        migrations.CreateModel(
            name='RentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي الدخل')),
                ('generated_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التقرير')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.building', verbose_name='المبنى')),
            ],
            options={
                'verbose_name': 'تقرير الإيجار',
                'verbose_name_plural': 'تقارير الإيجار',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('id_card', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهوية')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='tenant_pictures/', verbose_name='صورة المستأجر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'مستأجر',
                'verbose_name_plural': 'المستأجرون',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['phone_number'], name='rental_mana_phone_n_02f61a_idx')],
            },
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.tenant', verbose_name='المستأجر'),
        ),
        migrations.CreateModel(
            name='TenantBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='اسم البنك')),
                ('account_number', models.CharField(max_length=50, verbose_name='رقم الحساب')),
                ('iban', models.CharField(max_length=34, verbose_name='رقم البنك الإيباني')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.tenant', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'حساب مصرفي للمستأجر',
                'verbose_name_plural': 'حسابات مصرفية للمستأجرين',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('Office', 'مكتب'), ('Apartment', 'شقة'), ('Shop', 'محل')], max_length=50, verbose_name='نوع الوحدة')),
                ('status', models.CharField(choices=[('Available', 'متاحة'), ('Rented', 'مؤجرة'), ('Maintenance', 'تحت الصيانة')], default='Available', max_length=50, verbose_name='الحالة')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='رقم الوحدة')),
                ('area', models.FloatField(verbose_name='المساحة')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإيجار الشهري')),
                ('image', models.ImageField(blank=True, null=True, upload_to='unit_images/', verbose_name='صورة الوحدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='rental_management.building', verbose_name='المبنى')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
                'ordering': ['building', 'number'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='تفاصيل المشكلة')),
                ('request_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الطلب')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تمت معالجتها')),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'طلب صيانة',
                'verbose_name_plural': 'طلبات الصيانة',
            },
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.unit', verbose_name='الوحدة'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['status', 'unit_type'], name='rental_mana_status_0c2f54_idx'),
        ),
    ]
