# Generated by Django 5.0.3 on 2024-11-29 09:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='الإجراء')),
                ('model_name', models.CharField(max_length=200, verbose_name='اسم النموذج')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرف العنصر')),
                ('user', models.CharField(max_length=200, verbose_name='المستخدم')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('details', models.TextField(blank=True, null=True, verbose_name='تفاصيل')),
            ],
            options={
                'verbose_name': 'سجل',
                'verbose_name_plural': 'السجلات',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LeaseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإيجار الشهري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'عقد إيجار',
                'verbose_name_plural': 'عقود الإيجار',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('related_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='النموذج المرتبط')),
                ('related_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='المعرف المرتبط')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('last_generated', models.DateTimeField(blank=True, null=True, verbose_name='آخر توليد')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المبني')),
                ('address', models.TextField(verbose_name='عنوان المبني')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='building_images/', verbose_name='صورة المبني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مبنى',
                'verbose_name_plural': 'المباني',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='rental_mana_name_f1629b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الإصدار')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('is_paid', models.BooleanField(default=False, verbose_name='مدفوعة')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='rental_management.leasecontract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('id_card', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهوية')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='tenant_pictures/', verbose_name='صورة المستأجر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'مستأجر',
                'verbose_name_plural': 'المستأجرون',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['phone_number'], name='rental_mana_phone_n_02f61a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الاشتراك')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الاشتراك الشهري')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='rental_management.tenant', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.tenant', verbose_name='المستأجر'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('Office', 'مكتب'), ('Apartment', 'شقة'), ('Shop', 'محل')], max_length=50, verbose_name='نوع الوحدة')),
                ('status', models.CharField(choices=[('Available', 'متاحة'), ('Rented', 'مؤجرة'), ('Maintenance', 'تحت الصيانة')], default='Available', max_length=50, verbose_name='الحالة')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='رقم الوحدة')),
                ('area', models.FloatField(verbose_name='المساحة')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإيجار الشهري')),
                ('image', models.ImageField(blank=True, null=True, upload_to='unit_images/', verbose_name='صورة الوحدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='rental_management.building', verbose_name='المبنى')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
                'ordering': ['building', 'number'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تمت المعالجة')),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='rental_management.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'طلب صيانة',
                'verbose_name_plural': 'طلبات الصيانة',
                'ordering': ['-request_date'],
            },
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental_management.unit', verbose_name='الوحدة'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='rental_management.building', verbose_name='المبنى')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصاريف',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['building', 'date'], name='rental_mana_buildin_5103d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الدفع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('conract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rental_management.leasecontract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'مدفوعة',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['conract', 'payment_date'], name='rental_mana_conract_147199_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة التذكير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم إرساله')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='rental_management.leasecontract', verbose_name='العقد')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='rental_management.tenant', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'تذكير',
                'verbose_name_plural': 'التذكيرات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'is_sent'], name='rental_mana_tenant__c2b467_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['status', 'unit_type'], name='rental_mana_status_0c2f54_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['unit', 'is_resolved'], name='rental_mana_unit_id_df4749_idx'),
        ),
    ]
