# Generated by Django 5.0.2 on 2024-11-28 20:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الإصدار')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('is_paid', models.BooleanField(default=False, verbose_name='مدفوعة')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('related_model', models.CharField(blank=True, help_text='اسم النموذج المرتبط (مثل: LeaseContract أو Invoce)', max_length=100, null=True, verbose_name='النموذج المرتبط')),
                ('related_id', models.PositiveIntegerField(blank=True, help_text='معرف العنصر المرتبط في النموذج', null=True, verbose_name='المعرف المرتبط')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة التذكير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم إرساله')),
            ],
            options={
                'verbose_name': 'تذكير',
                'verbose_name_plural': 'التذكيرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('last_generated', models.DateTimeField(blank=True, null=True, verbose_name='آخر توليد')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الاشتراك')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الاشتراك الشهري')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='contract',
        ),
        migrations.DeleteModel(
            name='Notifiction',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='rentreport',
            name='building',
        ),
        migrations.RemoveField(
            model_name='tenantbankaccount',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='leasecontract',
            name='tenant',
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'مصروف', 'verbose_name_plural': 'المصاريف'},
        ),
        migrations.AlterModelOptions(
            name='leasecontract',
            options={'ordering': ['-start_date'], 'verbose_name': 'عقد إيجار', 'verbose_name_plural': 'عقود الإيجار'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'طلب صيانة', 'verbose_name_plural': 'طلبات الصيانة'},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='related_model',
            field=models.CharField(blank=True, help_text='اسم النموذج المرتبط بالسجل', max_length=100, null=True, verbose_name='النموذج المرتبط'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='rental_management.building', verbose_name='المبنى'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ النهاية'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='description',
            field=models.TextField(verbose_name='وصف المشكلة'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='تمت المعالجة'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='rental_management.unit', verbose_name='الوحدة'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['building', 'date'], name='rental_mana_buildin_5103d5_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['is_resolved'], name='rental_mana_is_reso_0bf268_idx'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='rental_management.leasecontract', verbose_name='العقد'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='rental_management.leasecontract', verbose_name='العقد'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='RentReport',
        ),
        migrations.DeleteModel(
            name='TenantBankAccount',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['contract', 'due_date'], name='rental_mana_contrac_6ae20d_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['is_sent'], name='rental_mana_is_sent_23e4d7_idx'),
        ),
    ]
