# Generated by Django 5.1.3 on 2024-11-24 19:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasecontract',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='leasecontract',
            name='unit',
        ),
        migrations.AlterModelOptions(
            name='rentreport',
            options={'verbose_name': 'تقرير الإيجار', 'verbose_name_plural': 'تقارير الإيجار'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'وحدة', 'verbose_name_plural': 'الوحدات'},
        ),
        migrations.AddField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='unit_images/', verbose_name='صورة الوحدة'),
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.TextField(verbose_name='عنوان المبنى'),
        ),
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='building_images/', verbose_name='صورة المبنى'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم المبنى'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.building', verbose_name='المبنى'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='وصف المصروف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='تفاصيل المشكلة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='request_date',
            field=models.DateField(verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='rentreport',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.building', verbose_name='المبنى'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='tenantbankaccount',
            name='account_number',
            field=models.CharField(max_length=50, verbose_name='رقم الحساب'),
        ),
        migrations.AlterField(
            model_name='tenantbankaccount',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='اسم البنك'),
        ),
        migrations.AlterField(
            model_name='tenantbankaccount',
            name='iban',
            field=models.CharField(max_length=34, verbose_name='رقم الآيبان'),
        ),
        migrations.AlterField(
            model_name='tenantbankaccount',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental_management.tenant', verbose_name='المستأجر'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='area',
            field=models.FloatField(verbose_name='المساحة (م²)'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.building', verbose_name='المبنى'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'متاحة'), ('rented', 'مؤجرة'), ('maintenance', 'تحت الصيانة')], default='available', max_length=50, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('office', 'مكتب'), ('apartment', 'شقة'), ('shop', 'محل')], max_length=50, verbose_name='نوع الوحدة'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='LeaseContract',
        ),
    ]
