# Generated by Django 5.1.3 on 2024-11-22 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasecontract',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='مستند العقد'),
        ),
        migrations.AddField(
            model_name='units',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متاحة'),
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(max_length=200, verbose_name='عنوان المبني'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المستحق')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('is_paid', models.BooleanField(default=False, verbose_name='مدفوع')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.leasecontract', verbose_name='العقد')),
            ],
        ),
    ]
