# Generated by Django 5.0.3 on 2024-11-30 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='message',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='الرسالة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagelog',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإرسال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagelog',
            name='status',
            field=models.CharField(choices=[('sent', 'تم الإرسال'), ('failed', 'فشل')], default='sent', max_length=50, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='recipient',
            field=models.CharField(max_length=200, verbose_name='المستلم'),
        ),
    ]
