# Generated by Django 5.1.3 on 2024-11-24 07:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0002_leasecontract_document_units_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='building_images/', verbose_name='صورة المبني'),
        ),
        migrations.AddField(
            model_name='building',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('avaliable', 'متاحة'), ('rented', 'مؤجرة'), ('maintenance', 'تحت الصيانة')], max_length=50, verbose_name='نوع الوحدة')),
                ('status', models.CharField(choices=[('avaliable', 'متاحة'), ('rented', 'مؤجرة'), ('maintenance', 'تحت الصيانة')], default='available', max_length=50, verbose_name='الحالة')),
                ('number', models.CharField(max_length=50, verbose_name='رقم الوحدة')),
                ('area', models.FloatField(verbose_name='المساحة (متر مربع)')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإيجار الشهري')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.building', verbose_name='المبني')),
            ],
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.unit', verbose_name='الوحدة'),
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
