# Generated by Django 5.0.2 on 2024-12-01 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0002_messagelog_message_messagelog_sent_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LatePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('days_late', models.PositiveIntegerField(verbose_name='عدد الأيام المتأخرة')),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='غرامة التأخير')),
            ],
            options={
                'verbose_name': 'غرامة تأخير',
                'verbose_name_plural': 'غرامات التأخير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='annualrentdetail',
            name='unit',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='DailyPaymentLog',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='latepaymnet',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='MessageLog',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='conract',
        ),
        migrations.RemoveField(
            model_name='reminderlog',
            name='reminder',
        ),
        migrations.RemoveField(
            model_name='scheduledreminder',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='scheduledreminder',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='scheduledreminder',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='SystemEvent',
        ),
        migrations.DeleteModel(
            name='SystemStatistics',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='maintenancefeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'تقييم صيانة', 'verbose_name_plural': 'تقييمات الصيانة'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'طلب الصيانة', 'verbose_name_plural': 'طلبات الصيانة'},
        ),
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'ordering': ['key'], 'verbose_name': 'إعداد النظام', 'verbose_name_plural': 'إعدادات النظام'},
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='rental_mana_contrac_f88f51_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenancerequest',
            name='rental_mana_unit_id_53a6a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='rental_mana_is_read_668bf6_idx',
        ),
        migrations.RemoveIndex(
            model_name='reminder',
            name='rental_mana_tenant__c2b467_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenant',
            name='rental_mana_phone_n_02f61a_idx',
        ),
        migrations.RemoveIndex(
            model_name='unit',
            name='rental_mana_status_587c44_idx',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='maintenancefeedback',
            name='maintenance_request',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='resolved_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_model',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='report',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_scheduled',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='tags',
        ),
        migrations.AddField(
            model_name='building',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='أنشي بواسطة'),
        ),
        migrations.AddField(
            model_name='building',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='عدل بواسطة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='أنشي بواسطة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='مدفوعة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='عدل بواسطة'),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='أنشي بواسطة'),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='عدل بواسطة'),
        ),
        migrations.AddField(
            model_name='maintenancefeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='أنشي بواسطة'),
        ),
        migrations.AddField(
            model_name='maintenancefeedback',
            name='maintenance_requests',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='rental_management.maintenancerequest', verbose_name='طلب الصيانة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancefeedback',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='عدل بواسطة'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='أنشي بواسطة'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='عدل بواسطة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='أنشي بواسطة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='عدل بواسطة'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='أنشي بواسطة'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='عدل بواسطة'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='أنشي بواسطة'),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='عدل بواسطة'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='أنشي بواسطة'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='عدل بواسطة'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='أنشي بواسطة'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='عدل بواسطة'),
        ),
        migrations.AddField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='أنشي بواسطة'),
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='عدل بواسطة'),
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(max_length=255, verbose_name='عنوان المبنى'),
        ),
        migrations.AlterField(
            model_name='building',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء'),
        ),
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='وصف المبنى'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='buildings/', verbose_name='صورة المبنى'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم المبنى'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='rental_management.tenant', verbose_name='المستأجر'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='rental_management.unit', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='maintenancefeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء'),
        ),
        migrations.AlterField(
            model_name='maintenancefeedback',
            name='rating',
            field=models.PositiveIntegerField(default=5, verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية')], default='low', max_length=50, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية')], default='low', max_length=50, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='rental_management.leasecontract', verbose_name='العقد'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='تم الإرسال'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='message',
            field=models.TextField(verbose_name='رسالة التذكير'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='area',
            field=models.FloatField(verbose_name='مساحة (م2)'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'متاحة'), ('rented', 'مستأجرة'), ('reserved', 'محجوزة')], default='available', max_length=50, unique=True, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('office', 'مكتب'), ('apartment', 'شقة'), ('store', 'محل'), ('warehouse', 'مستودع')], max_length=50, verbose_name='نوع الوحدة'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_paid', 'due_date'], name='rental_mana_is_paid_99e470_idx'),
        ),
        migrations.AddIndex(
            model_name='leasecontract',
            index=models.Index(fields=['is_active', 'tenant', 'unit'], name='rental_mana_is_acti_14d44a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['phone_number', 'email'], name='rental_mana_phone_n_9bd3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['status', 'unit_type', 'building'], name='rental_mana_status_802055_idx'),
        ),
        migrations.AddField(
            model_name='latepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='أنشي بواسطة'),
        ),
        migrations.AddField(
            model_name='latepayment',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='late_payment', to='rental_management.invoice', verbose_name='الفاتورة'),
        ),
        migrations.AddField(
            model_name='latepayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='عدل بواسطة'),
        ),
        migrations.DeleteModel(
            name='AnnualRentDetail',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='LatePaymnet',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='ReminderLog',
        ),
        migrations.DeleteModel(
            name='ScheduledReminder',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
