# Generated by Django 5.0.2 on 2024-11-28 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0002_invoice_notification_reminder_report_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='reminder',
            name='rental_mana_is_sent_23e4d7_idx',
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='tenant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rental_management.tenant', verbose_name='المستأجر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='tenant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='rental_management.tenant', verbose_name='الأشخاص'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='rental_management.tenant', verbose_name='المستأجر'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['tenant', 'is_sent'], name='rental_mana_tenant__c2b467_idx'),
        ),
    ]
