# Generated by Django 5.0.2 on 2024-11-25 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0002_remove_leasecontract_tenant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantbankaccount',
            options={'verbose_name': 'حساب مصرفي للمستأجر', 'verbose_name_plural': 'حسابات مصرفية للمستأجرين'},
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='description',
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.TextField(verbose_name='عنوان المبني'),
        ),
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='building_images/', verbose_name='صورة المبني'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم المبني'),
        ),
        migrations.AlterField(
            model_name='tenantbankaccount',
            name='iban',
            field=models.CharField(max_length=34, verbose_name='رقم البنك الإيباني'),
        ),
        migrations.AlterField(
            model_name='tenantbankaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.tenant', verbose_name='المستأجر'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='area',
            field=models.FloatField(verbose_name='المساحة'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي الشهري'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('Available', 'متاحة'), ('Occupied', 'مؤجرة'), ('Under Maintenance', 'تحت الصيانة')], default='Available', max_length=50, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('Apartment', 'شقة'), ('Office', 'مكتب'), ('Shop', 'محل')], max_length=50, verbose_name='نوع الوحدة'),
        ),
    ]
