# Generated by Django 5.0.2 on 2024-11-28 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0003_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='active_contracts',
            field=models.ManyToManyField(related_name='active_tenants', to='rental_management.leasecontract', verbose_name='العقود النشطة'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='البريد الإلكتروني'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='الاسم الكامل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='profile_picture_preview',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_profile_pictures/', verbose_name='صورة الملف الشخصي'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
