# Generated by Django 5.1.3 on 2024-11-24 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0003_building_created_at_building_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'مبنى', 'verbose_name_plural': 'المباني'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'مستأجر', 'verbose_name_plural': 'المستأجرون'},
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='تاريخ المصروف')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.building', verbose_name='المبني')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصاريف',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='تفاصيل المشكلة')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تمت معالجتها')),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'طلب صيانة',
                'verbose_name_plural': 'طلبات الصيانة',
            },
        ),
        migrations.CreateModel(
            name='RentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي الدخل')),
                ('generated_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التقرير')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.building', verbose_name='المبني')),
            ],
            options={
                'verbose_name': 'تقرير إيجار',
                'verbose_name_plural': 'تقارير الإيجار',
            },
        ),
        migrations.CreateModel(
            name='TenantBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200, verbose_name='اسم البنك')),
                ('account_number', models.CharField(max_length=200, verbose_name='رقم الحساب')),
                ('iban', models.CharField(max_length=200, verbose_name='رقم الايبان')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_management.tenant', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'الحسابات البنكية',
            },
        ),
    ]
