# Generated by Django 5.0.3 on 2024-12-02 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0004_payment_alter_building_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancefeedback',
            name='maintenance_requests',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='rental_management.maintenancerequest', verbose_name='طلب الصيانة'),
        ),
    ]
