# Generated by Django 5.0.3 on 2024-11-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0005_auditlog_alter_building_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='id_card',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_pictures/', verbose_name='صورة المستأجر'),
        ),
    ]
