# Generated by Django 5.0.3 on 2024-11-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0007_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='request_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الطلب'),
        ),
    ]
