# Generated by Django 5.0.3 on 2024-11-28 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0008_alter_maintenancerequest_request_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['full_name'], 'verbose_name': 'مستأجر', 'verbose_name_plural': 'المستأجرون'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['building', 'number'], 'verbose_name': 'وحدة', 'verbose_name_plural': 'الوحدات'},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='rental_management.building', verbose_name='المبنى'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الوحدة'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['name'], name='rental_mana_name_f1629b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['phone_number'], name='rental_mana_phone_n_02f61a_idx'),
        ),
    ]
