# Generated by Django 5.0.3 on 2024-11-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_management', '0009_alter_tenant_options_alter_unit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-id'], 'verbose_name': 'مرفق', 'verbose_name_plural': 'المرفقات'},
        ),
        migrations.AlterModelOptions(
            name='notifiction',
            options={'ordering': ['-created_at'], 'verbose_name': 'إشعار', 'verbose_name_plural': 'الإشعارات'},
        ),
        migrations.AlterField(
            model_name='unit',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإيجار الشهري'),
        ),
    ]
