# Generated by Django 5.0.3 on 2025-01-03 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='تاريخ الاصدار')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('paid', 'مدفوعة'), ('unpaid', 'غير مدفوعة')], default='unpaid', max_length=20, verbose_name='الحالة')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='العقد')),
            ],
        ),
    ]
