# Generated by Django 5.0.3 on 2025-01-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الوحدة')),
                ('type', models.CharField(choices=[('residential', 'سكني'), ('commercial', 'تجاري')], max_length=50, verbose_name='نوع الوحدة')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المساحة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('occupied', models.BooleanField(default=False, verbose_name='مشغولة')),
            ],
        ),
    ]
