# Generated by Django 5.0.3 on 2025-01-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العقار')),
                ('propert_type', models.CharField(choices=[('apartment', 'شقة'), ('office', 'مكتب'), ('shop', 'محل')], max_length=10, verbose_name='نوع العقار')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('address', models.TextField(verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'العقارات',
            },
        ),
    ]
